//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaSummitInventorySystem {
    
    
    public partial class aspnetProductInformationOpeningBalance {
        
        /// <summary>
        /// ProductSubMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MegaSummitInventorySystem.include.ProductSubMenu ProductSubMenu;
        
        /// <summary>
        /// ProductSubMenuAjax1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MegaSummitInventorySystem.include.ProductSubMenuAjax ProductSubMenuAjax1;
        
        /// <summary>
        /// repList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater repList;
    }
}
